CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  display_name VARCHAR(50) NOT NULL,
  quick_token VARCHAR(40) NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS recurring_expenses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  category VARCHAR(50) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  person VARCHAR(50) NOT NULL,
  split_mode VARCHAR(20) NOT NULL DEFAULT 'esit',
  ozel_tutar DECIMAL(12,2) NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS expenses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  expense_date DATE NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  category VARCHAR(50) NOT NULL,
  description VARCHAR(255),
  paid_by VARCHAR(50) NOT NULL,
  split_mode VARCHAR(20) NOT NULL,
  owed_by_other DECIMAL(12,2) NOT NULL DEFAULT 0,
  recurring_id INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (recurring_id) REFERENCES recurring_expenses(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS investment_positions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  type VARCHAR(50) NOT NULL,
  ticker VARCHAR(20) NULL,
  exchange VARCHAR(10) NOT NULL DEFAULT 'BIST',
  person VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS investment_entries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  position_id INT NOT NULL,
  entry_date DATE NOT NULL,
  kind VARCHAR(30) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  quantity DECIMAL(14,4) NULL,
  price_per_unit DECIMAL(14,4) NULL,
  note VARCHAR(255),
  FOREIGN KEY (position_id) REFERENCES investment_positions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS price_cache (
  ticker VARCHAR(30) PRIMARY KEY,
  price DECIMAL(14,4) NOT NULL,
  fetched_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settlements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  settle_date DATE NOT NULL,
  from_person VARCHAR(50) NOT NULL,
  to_person VARCHAR(50) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  note VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS salary_entries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  person VARCHAR(50) NOT NULL,
  month CHAR(7) NOT NULL,
  salary_amount DECIMAL(12,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY person_month (person, month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS salary_contributions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  salary_entry_id INT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  entry_date DATE NOT NULL,
  note VARCHAR(255),
  FOREIGN KEY (salary_entry_id) REFERENCES salary_entries(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
